### ISSUE TITLE
ORC output/input support

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#153]
Ability to write output in ORC file format

**Comment by lyogev** [comment]
Not planned at the moment, if anyone wishes to help write this it can be very helpful.

**Comment by lyogev** [comment]
It's possible now with the new generic file input

**Comment by tooptoop4** [comment]
readme does not mention anything about ORC

**Comment by lyogev** [comment]
Add to your metric config file:
```
output:
  - dataFrameName: df
    outputType: File
    format: orc
    outputOptions:
      saveMode: Overwrite
      path: file.orc
     ....
```

Check out [metric full sample config file](https://github.com/YotpoLtd/metorikku/blob/master/config/metric_config_sample.yaml)
