### ISSUE TITLE
'partition by' same values as input filenames (not folders)

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#161]
input:
folderA/20180201.csv
folderA/20180202.csv
folderA/20180203.csv

with single metorikku jar run want to get output in parquet of:
date=20180201/a.parquet
date=20180202/a.parquet
date=20180203/a.parquet

**Comment by lyogev** [comment]
You can use partitionby with your date field.
Or you can use named outputs if you know in advance your dates.

**Comment by tooptoop4** [comment]
correct

**Comment by lyogev** [comment]
It's possible to do it with something we call fileDateRange.
You can use it like this:
```
file_date_range:
      template: path/%s.csv
      date_range:
        format: yyyyMMdd
        startDate: 20180201
        endDate: 20180203
```
