### ISSUE TITLE
download input from sftp

### ISSUE THREAD

**Issue by rkravinderkumar05** [YotpoLtd/metorikku#208]
Is there any way i can give input dataframe path as sftp server and metorikku downloads the file and use it?

**Comment by lyogev** [comment]
Yes.
If you're running metorikku with spark-submit use the following command:
```
spark-submit --packages com.springml:spark-sftp_2.11:1.1.5 --class com.yotpo.metorikku.Metorikku metorikku.jar -c config.yaml
```

Then in your config file in the input define:
```
input_sftp:
    file:
      path: /sample.csv
      format: com.springml.spark.sftp
      options:
            host: SFTP_HOST
            username: SFTP_USER
            password: SFTP_PASSWORD
```

Check out the documentation of all available options here:
https://github.com/springml/spark-sftp
