### ISSUE TITLE
Need a sample test metrics config 

### ISSUE THREAD

**Issue by jumpnrun88** [YotpoLtd/metorikku#212]
Is it possible to have a testmetrics configuration which contain all the configuration . 

We have currently limited documentation for the testing of the metric files . 

- The documentation has one example config file of job and metric

**Comment by lyogev** [comment]
We'll add it soon to the code but for now:
```
# Path to metric file
metric: "some_metric.yaml"
# Paths to all the different mock inputs
mocks:
  # Name of the input to be used in the metric queries
- name: input1
  # Path to the mock file
  path: mocks/input1.jsonl
- name: input2
  path: mocks/input2.jsonl
  # Indicated this mocks a streaming input
  streaming: true
# Add variables 
params:
  variables:
    var1: value1
    var2: value2
# List of assertions    
tests:
  # Name of the step from the metric to assert
  step1:
  # Per row all different cloumns and their values
  - col1: val1
    col2: val2
  - col1: val3
    col2: val4
  step2:
  - col3: val5
  - col3: val6
```
