### ISSUE TITLE
support for reading tables from Glue metastore

### ISSUE THREAD

**Issue by moshir** [YotpoLtd/metorikku#346]
Hi folks ! 
Is there any support for reading tables from Glue metastore (using metorikku on EMR)

**Comment by lyogev** [comment]
I never tried this but if you're in EMR and glue is connected it will simply work...

**Comment by moshir** [comment]
How do you specify a table as input then ?

**Comment by lyogev** [comment]
You don't need to define anything as input.
Just use table names from glue inside your sqls.

**Comment by cyrillay** [comment]
Hello @lyogev 

I can't manage to read from tables from the Glue metastore.

As you say, if I understand correctly, I don't need to define anything as input.
I have the following as `job_config.yaml` :
```yaml
metrics:
  - s3://.../metrics_config.yaml
output:
  jdbc:
    connectionUrl: ${JDBC_URL}
    user: root
    password: ${DB_PASSWORD}
    driver: "com.mysql.jdbc.Driver"
    options:
      truncate: true

appName: test_ingestion
showPreviewLines: 20
showQuery: true
```

In `metrics_config.yaml`, I use this syntax : 

```yaml
steps:
- dataFrameName: df_asset
  sql: SELECT * FROM my_database.table_name
output:
- dataFrameName: df_table_name
  outputType: JDBC
  outputOptions:
    saveMode: Overwrite
    dbTable: table_name
```

When I run this, I get the issue that the table can't be found : 
`org.apache.spark.sql.AnalysisException: Table or view not found: my_database.table_name; line 1 pos 14;`

I tried replacing the `SELECT * FROM ...` with `SHOW DATABASES` to see if the database is detected correctly, but I get the following output : 
```
root
 |-- namespace: string (nullable = false)

+---------+
|namespace|
+---------+
|default  |
+---------+
```

I can't understand why I can't see my databases here.

Something is also weird, on that same EMR cluster, if I ssh into the master node, and run `SHOW DATABASES` in a `spark-sql` prompt, I can **indeed see my databases**, so it works correctly.

Do you have any idea ? Any help would be much appreciated !

Thanks you in advance.
