### ISSUE TITLE
hide sensitive config from logs

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#399]
If i have an input yaml connecting to jdbc source like:
```
inputs:
  somedb:
    jdbc:
      connectionUrl: jdbc:jtds:redact
      user: someuser
      password: somepass
```

the log has
```
2020-12-08 17:01:28,076 [main] INFO  com.yotpo.metorikku.Job - these are the config inputs: Some(Map(.....somepass
```

ideally this should be printed as ****** in the log
