### ISSUE TITLE
Support loading inputs from different sources

### ISSUE THREAD

**Issue by eyalkenig** [YotpoLtd/metorikku#45]
It would be awsome to support more types as inputs.
Part of this would be moving the dateRange to be an input type.

here some examples for the inputs section in the configuration file that comes to mind:
```
# Sources can be used as types for inputs
sources:
  name: my_mongo
     type: mongo
     credentials: user1/pass1
  name: big_mysql
     type: mysql
     db_name: movies_db
     username: theusername
     password: thepassword

# Parquet or JSON Tables files paths
inputs:
  input_1: 
    type: file
    path: parquet/input_1.parquet
  input_2: 
    type: source
    name: my_mongo
    collection: movies
  input_3: 
    type: source
    name: big_mysql
    query: "SELECT * FROM movies LIMIT 100"
  input_4: 
    type: source
    name: big_mysql
    table: movies
  input_5: 
    type: file_date_range
    template: parquet/%s/input_1.parquet
    dateRange:
      format: yyyy/MM/dd
      startDate: 2017/09/01
      endDate: 2017/09/20
  input_6: 
    type: file_range
    template: parquet/%s/input_1.parquet
    array:
       - development
       - staging
       - production
```
